### ISSUE TITLE
Transient "file returned by server too large" error

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#5770]
### General summary/comments (optional)

I've been seeing this transient error more and more often in CI:
```
No information from Hackage index, updating
Selected mirror https://hackage.haskell.org/
Downloading root
Waiting to acquire cache lock on /home/runner/.stack/pantry/hackage/hackage-security-lock
Acquired cache lock on /home/runner/.stack/pantry/hackage/hackage-security-lock
Released cache lock on /home/runner/.stack/pantry/hackage/hackage-security-lock
Selected mirror https://hackage.haskell.org/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
file returned by server too large: <repo>/01-index.tar.gz (expected exactly 107277022 bytes)
```
A rerun usually fixes it. I'm not sure if the issue is on the Hackage or Stack side, so I'm posting here for now. If it's a Hackage issue, it might be nice for Stack to automatically retry a couple times?

### Steps to reproduce
Flaky

**Comment by avdv** [comment]
Hi.

Recently, I have been hitting the same error [here](https://github.com/tweag/rules_haskell/actions/runs/5748825042/job/15582462052?pr=1874) and also [here](https://github.com/tweag/rules_haskell/actions/runs/5735667433/job/15543786437?pr=1926):
```
Selected mirror https://hackage.haskell.org/
Downloading root
Waiting to acquire cache lock on /Users/runner/.stack/pantry/hackage/hackage-security-lock
Acquired cache lock on /Users/runner/.stack/pantry/hackage/hackage-security-lock
Released cache lock on /Users/runner/.stack/pantry/hackage/hackage-security-lock
Selected mirror https://hackage.haskell.org/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
file returned by server too large: <repo>/01-index.tar.gz (expected exactly 115595549 bytes)
ERROR: /private/tmp/bazel-run-start-script/WORKSPACE:36:15: fetching _stack_update rule //external:rules_haskell_stack_update: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_runner/9e75b231e6ff36fa9852d8b1f1fbcd40/external/rules_haskell/haskell/cabal.bzl", line 2320, column 28, in _stack_update_impl
		_execute_or_fail_loudly(repository_ctx, [stack_cmd, "update"])
	File "/private/var/tmp/_bazel_runner/9e75b231e6ff36fa9852d8b1f1fbcd40/external/rules_haskell/haskell/private/workspace_utils.bzl", line 27, column 13, in execute_or_fail_loudly
		fail("\n".join(["Command failed: " + " ".join(arguments), exec_result.stderr]))
Error in fail: Command failed: /private/var/tmp/_bazel_runner/9e75b231e6ff36fa9852d8b1f1fbcd40/external/rules_haskell_stack/stack update
```

**Comment by mpilgrem** [comment]
The `file returned by server too large: <repo>/01-index.tar.gz (expected exactly 115595549 bytes)` is a message produced by the `hackage-security` package (see `Hackage.Security.Client.Repository.Remote.FileTooLarge`), thrown by `Hackage.Security.Client.Repository.Remote.execBodyReader`. So, I think this is likely an issue with Hackage.
